line_length: 100
function_body_length: 150
type_body_length: 300
file_length: 500

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - i
    - s
    - l
    - m

# Opt-in to additional rules you want
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - sorted_imports
