name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Unit Tests
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.0.app/Contents/Developer
    
    - name: Show Xcode version
      run: xcode-build -version
    
    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/Library/Caches/org.swift.swiftpm
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    
    - name: Cache Xcode DerivedData
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/*.xcodeproj/project.pbxproj') }}
        restore-keys: |
          ${{ runner.os }}-xcode-deriveddata-
    
    - name: Install dependencies
      run: |
        # Resolve Swift Package dependencies
        xcodebuild -resolvePackageDependencies -project Argus.xcodeproj
    
    - name: Build project
      run: |
        xcodebuild \
          -project Argus.xcodeproj \
          -scheme Argus \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -configuration Debug \
          build-for-testing
    
    - name: Run unit tests
      run: |
        xcodebuild \
          -project Argus.xcodeproj \
          -scheme Argus \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
          -configuration Debug \
          test-without-building \
          -skip-testing:ArgusUITests
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
        retention-days: 7